### ISSUE TITLE
Problem during installation - rJava was built under R version 3.6.2

### ISSUE THREAD

**Issue by harbi811** [JosephCrispell/homoplasyFinder#13]
When I try and install homoplasyFinder using devtools:
`devtools::install_github("JosephCrispell/homoplasyFinder")`

I get the following error:
`Error: (converted from warning) package ‘rJava’ was built under R version 3.6.2
Execution halted`

I am running on the system below
- platform    -   x86_64-apple-darwin15.6.0                      
- os    -    darwin15.6.0                
- version.string  - R version 3.6.1 (2019-07-05)

**Comment by harbi811** [comment]
I am really sorry about this. I had not seen a previous issue asking about a docker/singularity container.

**Comment by JosephCrispell** [comment]
Hi harbi,

No problem at all - only seening this issue now - sorry for not responding sooner!
