### ISSUE TITLE
Is there a homoplasyFinder docker container?

### ISSUE THREAD

**Issue by flashton2003** [JosephCrispell/homoplasyFinder#5]
Hi Joe,

I'm trying to get up and running with homoplasyFinder, having some installation troubles with rJava. I'm sure that after some more tinkering I'll get it working, but I was just wondering if there is a docker/singularity container?

Ta,

Phil

**Comment by JosephCrispell** [comment]
Hi Phil,

Thanks for trying `homoplasyFinder`, sorry to hear you're having trouble with `rJava`. Unfortunately, `homoplasyFinder` doesn't current have a docker.

You can use `homoplasyFinder` without R, either in the command line using the [command line version](https://github.com/JosephCrispell/homoplasyFinder/raw/master/inst/java/HomoplasyFinder.jar) or through its GUI, using [this](https://github.com/JosephCrispell/Java/raw/master/ExecutableJarFiles/HomoplasyFinder-GUI.jar) version. You'll find instructions for working with `homoplasyFinder` in the command line or via the gui [here](https://github.com/JosephCrispell/homoplasyFinder/wiki/Installation-and-running#homoplasyfinder-in-the-command-line).

Also, there are some instructions to help you try and get `rJava` working properly [here](https://github.com/JosephCrispell/homoplasyFinder/wiki/Issues#cant-get-rjava-to-install).

Let me know how you get on.

Thanks,

Joe

**Comment by flashton2003** [comment]
Hi Joe,

That's awesome, I used the GUI instead and it ran well on >2000 L4 TB genomes. So quick!

Cheers!

Phil

**Comment by JosephCrispell** [comment]
Hi Phil,

That's great, really glad that it worked ok and I hope the results are meaningful. Let me know if you have any other issues.

I'll assume you're happy for me to close the issue - let me know if not and I'll re-open it.

Thanks again for using `homoplasyFinder`!

Joe
