### ISSUE TITLE
noInconsistentSites is malformed?

### ISSUE THREAD

**Issue by flashton2003** [JosephCrispell/homoplasyFinder#6]
Hi Joe,

I just tried to read the noInconsistentSites file and it seems to be malformed. Maybe easiest if I give you the original alignment and treefile to see if it's replicable for you?

[Alignment](https://www.dropbox.com/s/dcmbd5qej0nnepk/2019.11.04_all_L4_masked.snp-sites.fa.for_joe.gz?dl=0) (68 Mb gzipped).

[Tree](https://www.dropbox.com/s/5atrs6g5pbvpxxh/2019.11.04_all_L4_masked.snp-sites.fa.tree?dl=0).

Ta,

Phil

**Comment by JosephCrispell** [comment]
Hi Phil,

So it does! That is very weird, I'll fix it and let you know when I have updated the code.

Thanks for pointing this out!

Just for my reference, this is what my `noInconsistentSites_DATE.fasta` file looks like:
    
    3231 3938 2031 3035 3035 360a 3e31 3634
    3934 2d45 5252 3332 3536 3132 370a 4341
    ...

Also, this file should be called: `sequences_withoutHomoplasies_DATE.fasta`.

Joe

**Comment by JosephCrispell** [comment]
Hi Phil,

Flip, that was a tricky bug to track down. Thanks so much for pointing it out, it should be fixed now. Note that the `noInconsistentSites_DATE.fasta` name has been slightly changed to the following `sequences_noInconsistentSites_DATE.fasta`.

I have updated all versions of `homoplasyFinder` ([command line](https://github.com/JosephCrispell/Java/raw/master/ExecutableJarFiles/HomoplasyFinder.jar), [GUI](https://github.com/JosephCrispell/Java/raw/master/ExecutableJarFiles/HomoplasyFinder-GUI.jar) and [R package](https://github.com/JosephCrispell/homoplasyFinder)).

Let me know if it works on your end now.

Thanks!

Joe

**Comment by flashton2003** [comment]
Hi Joe,

Yeah, that works well now. Thanks for the quick fix!

Phil
